version: "3"

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9094:9094"
    environment:
      # HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092,OUTSIDE://192.168.0.100:9094
      KAFKA_LISTENERS: PLAINTEXT://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "airtable:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/logs
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"

  connect:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        version: 0.8.8
    command: "/opt/kafka/bin/connect-standalone.sh /conf/connect-standalone.properties /conf/airtable.properties"
    volumes:
      - ./conf:/conf
    depends_on:
      - kafka
